### ISSUE TITLE
Cursor icons missing

### ISSUE THREAD

**Issue by seb128** [ubuntu/yaru#2451]
The bug has been reported initially on https://bugs.launchpad.net/ubuntu/+source/chromium-browser/+bug/1892085

On ubuntu focal (or current serie)

Install the chromium snap and try the MDN cursor demos at https://developer.mozilla.org/en-US/docs/Web/CSS/cursor for cursor: wait and cursor: grab. (Click the "cursor: wait;" or "cursor: grab;" button, then move the mouse over the blue box on the right to see the cursor set by that CSS option.), the CSS-set wait spinner and grab hand cursors are using the Adwaita theme

it seems because the 'wait' and 'grab' cursor are missing from yaru (firefox handle those by fallbacking e.g 'wait' to 'watch'), one option would be to symlink or copy those to the other names?

The following testcase is identical using gtk
$ python3 -c "from gi.repository import Gtk,Gdk,GObject; window = Gtk.Window(); window.show_all(); window.get_window().set_cursor(Gdk.Cursor.new_from_name(Gdk.Display.get_default(), 'wait')); Gtk.main()"

**Comment by Feichtmeier** [comment]
Thanks @seb128 for the report

We had similar issues in the last with gnome  baobab for example. The wait cursor always reverted to adwaita.
In other apps it was always working right. Then in baobab it was fixed with a recent gtk release. Maybe the gtk snap connected to the chromium snap is outdated?

**Comment by seb128** [comment]
The python command still shows the issue, also it's clear that there is no 'wait' file in the cursor directory for yaru, it should be easy to cp watch wait (and same for the .ani), which from local testing fixes the issue in the testcase at least

**Comment by seb128** [comment]
@Feichtmeier trying baobab it's still bugging using gtk 3.24.23-1ubuntu1 which is current, could you give some details on what version you tested?
the source is https://gitlab.gnome.org/GNOME/baobab/-/blob/master/src/baobab-window.vala#L123

**Comment by Feichtmeier** [comment]
> The python command still shows the issue, also it's clear that there is no 'wait' file in the cursor directory for yaru, it should be easy to cp watch wait (and same for the .ani), which from local testing fixes the issue in the testcase at least

Oh? Okay... I thought I remember baob working in gnome 3.38 but I can be wrong ofc
If this fixes it, can you create a PR?

**Comment by seb128** [comment]
>  If this fixes it, can you create a PR?

Could you maybe providing some guidance on what is needed? In adwaita they did symlinks in the cursors dir
grab -> hand
wait->watch

But the yaru source seems more complicated, what's the right place to edit, icons/Suru/cursors or icons/src/cursors? I'm unsure what I'm doing but I did a tentative fix there
https://github.com/ubuntu/yaru/pull/2453

**Comment by Feichtmeier** [comment]
I need to forward this to our Icon Crew:

@Jupiter007-43  @ubuntujaggers  could you please help @seb128 ?

**Comment by coxackie** [comment]
Not sure if related, but when I run `scummvm` using yaru cursor theme, it segfaults. It runs ok when adwaita cursor theme is used. Gnome 38.1, Arch linux, yaru 20.10.6.1.

**Comment by seb128** [comment]
> Not sure if related, but when I run `scummvm` using yaru cursor theme, it segfaults. It runs ok when adwaita cursor theme is used. Gnome 38.1, Arch linux, yaru 20.10.6.1.

That's probably a different issue, no such issue on Ubuntu using the scummvm snap or deb with the default yaru theme

**Comment by coxackie** [comment]
> > Not sure if related, but when I run `scummvm` using yaru cursor theme, it segfaults. It runs ok when adwaita cursor theme is used. Gnome 38.1, Arch linux, yaru 20.10.6.1.
> 
> That's probably a different issue, no such issue on Ubuntu using the scummvm snap or deb with the default yaru theme

hhhm, ok, I will use Adwaita cursor for the time being, and try to debug this a bit more.
