### ISSUE TITLE
Grabbing hand cursor is not recognizable

### ISSUE THREAD

**Issue by matthewpaulthomas** [ubuntu/yaru#855]
yaru-theme-* 18.10.4, Ubuntu Cosmic

The grabbing cursor is extremely abstract: there are no visible fingers, no visible knuckles, and the thumbtip is square.

![cursor hand](https://user-images.githubusercontent.com/19801137/45929570-820ad300-bf4b-11e8-9fa3-f7893717cb79.png) ![cursor hand enlarged](https://user-images.githubusercontent.com/19801137/45929668-dc586380-bf4c-11e8-8621-d6952db67d0f.png)

In earlier versions of Ubuntu, the cursor was much more recognizable as a hand: four visible fingers, three visible bottom knuckles, and the thumbtip is bent inward.

![cursor hand old](https://user-images.githubusercontent.com/19801137/45929636-6fdd6480-bf4c-11e8-9275-9a4d7514e8bd.jpg)

Neither of these are ideal: they show the kind of grip you’d make around a handlebar, which is very different from the kind of grip you’d make on a flat object on a flat surface, like a sheet of paper or a calculator resting on a real-life desktop. For that, the fingers should appear spread out.

[[Originally reported in the Yaru forum](https://discourse.ubuntu.com/t/call-for-participation-an-ubuntu-default-theme-lead-by-the-community/1545/1750).]

**Comment by Feichtmeier** [comment]
I think this should rather symbolize "grabbing" rather than using your finger

But I guess @snwh could tell us more about this idea

I personally prefer this grabbing to the finger, since a finger reminds me of drawing a picture or showing something

**Comment by Feichtmeier** [comment]
Also... the finger is used for links (OR if you activate single click in nautilus)
So with this grabbing hand you have 2 stages
1) hovering
2) pressing the mouse and grabbing the stuff
![peek 2018-09-23 18-07](https://user-images.githubusercontent.com/15329494/45930102-aec6e680-bf5b-11e8-86e0-3bbb7bb2f401.gif)

**Comment by snwh** [comment]
The issue with the hand's abstract design is something that I can fix. But the issues with the cursors being inconsistent or unclear between the types of dragging is something that ought to be addressed way upstream.

**Comment by Feichtmeier** [comment]
@matthewpaulthomas could you open this issue on the Suru repo? Thanks for taking the time to report it here first, I think my initial thought was just wrong to discuss the issues here. Sorry for the confusion.

**Comment by matthewpaulthomas** [comment]
Done. ^

**Comment by Feichtmeier** [comment]
Thank you!

**Comment by madsrh** [comment]
Reopening this issue as this isn't fixed. @ubuntujaggers ?

Regarding "way upstream bugs", it also seems like there's a long-press icon missing. Like in the gif below there's both a open hand and a grab hand. I'm not sure if it's possible to change that somewhere. 

Could the drag hand icon be white as in @matthewpaulthomas [first comment](https://github.com/ubuntu/yaru/issues/855#issue-362951647)?

![makeitbetter_dropbox_preview_ramotion](https://user-images.githubusercontent.com/3986894/72206563-cc40fc00-348f-11ea-942d-098888de73c6.gif)

**Comment by ubuntujaggers** [comment]
This is what I've got so far:

![image](https://user-images.githubusercontent.com/38893390/73319687-0a327400-4235-11ea-9aea-a9d024e12094.png)

Using the scripts I've got it working for everything except dragging windows, I'll try to work out why tomorrow :+1:

**Comment by Feichtmeier** [comment]
Fixed with #1825
